### ISSUE TITLE
Troubleshooting database corruption?

### ISSUE THREAD

**Issue by Mnkai** [tootsuite/mastodon#3991]
I'm running my mastodon instance inside docker (Arch Linux, using devicemapper since overlay2 causes severe performance degradation when updating permissions), and 'We're sorry, but something went wrong.' displays when I try to access preference page after upgrading instance to 1.4.6.

I tried to roll back - to version 1.4.3, but same problem persists. Also, notification feeds are not working ATM.

I'm suspecting database corruption. Is there any documentation I can use to fix my database without starting all over from scratch?

```
web_1        | [51c7cf62-b2c4-4c7c-87ae-ef5be2b01db9] method=GET path=/settings/preferences format=html controller=Settings::PreferencesController action=show status=500 error='ActionView::Template::Error: undefined method `each' for nil:NilClass' duration=63.13 view=0.00 db=14.45
web_1        | [51c7cf62-b2c4-4c7c-87ae-ef5be2b01db9]
web_1        | [51c7cf62-b2c4-4c7c-87ae-ef5be2b01db9] ActionView::Template::Error (undefined method `each' for nil:NilClass):
web_1        | [51c7cf62-b2c4-4c7c-87ae-ef5be2b01db9]     25:     = f.input :setting_default_privacy, collection: Status.visibilities.keys - ['direct'], wrapper: :with_label, include_blank: false, label_method: lambda { |visibility| safe_join([I18n.t("statuses.visibilities.#{visibility}"), content_tag(:span, I18n.t("statuses.visibilities.#{visibility}_long"), class: 'hint')]) }, required: false, as: :radio_buttons, collection_wrapper_tag: 'ul', item_wrapper_tag: 'li'
web_1        | [51c7cf62-b2c4-4c7c-87ae-ef5be2b01db9]     26:
web_1        | [51c7cf62-b2c4-4c7c-87ae-ef5be2b01db9]     27:   .fields-group
web_1        | [51c7cf62-b2c4-4c7c-87ae-ef5be2b01db9]     28:     = f.simple_fields_for :notification_emails, hash_to_object(current_user.settings.notification_emails) do |ff|
web_1        | [51c7cf62-b2c4-4c7c-87ae-ef5be2b01db9]     29:       = ff.input :follow, as: :boolean, wrapper: :with_label
web_1        | [51c7cf62-b2c4-4c7c-87ae-ef5be2b01db9]     30:       = ff.input :follow_request, as: :boolean, wrapper: :with_label
web_1        | [51c7cf62-b2c4-4c7c-87ae-ef5be2b01db9]     31:       = ff.input :reblog, as: :boolean, wrapper: :with_label
web_1        | [51c7cf62-b2c4-4c7c-87ae-ef5be2b01db9]
web_1        | [51c7cf62-b2c4-4c7c-87ae-ef5be2b01db9] app/lib/hash_object.rb:5:in `initialize'
web_1        | [51c7cf62-b2c4-4c7c-87ae-ef5be2b01db9] app/helpers/settings_helper.rb:42:in `new'
web_1        | [51c7cf62-b2c4-4c7c-87ae-ef5be2b01db9] app/helpers/settings_helper.rb:42:in `hash_to_object'
web_1        | [51c7cf62-b2c4-4c7c-87ae-ef5be2b01db9] app/views/settings/preferences/show.html.haml:28:in `block in _app_views_settings_preferences_show_html_haml___3788250387365372034_46925943346440'
web_1        | [51c7cf62-b2c4-4c7c-87ae-ef5be2b01db9] app/views/settings/preferences/show.html.haml:4:in `_app_views_settings_preferences_show_html_haml___3788250387365372034_46925943346440'
streaming_1  | verb 404be05d-c6d0-495b-8bf4-9849c8e723f2 Ending stream for 1

```

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [x] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by Mnkai** [comment]
Update, found some more logs on Sidekiq...

```
From SalmonWorker,
Parameter: 1, "<?xml version=\"1.0\"?>\n<me:env xmlns:me=\"http://salmon-protocol.org/ns/magic-env\">\n <me:data type=\"application/atom+xml\">(BASE64_ENCODED_DATA_HERE)
Error: NoMethodError: undefined method `[]' for nil:NilClass

```

**Comment by unarist** [comment]
Looks like settings record of that account is corrupted. It's stored in `settings` table by user and setting group. For example, settings for account 3 can be queried like this:

```
mastodon_development=# SELECT id, var, value from settings where thing_id = 3;
 id |         var         |          value
----+---------------------+--------------------------
  7 | notification_emails | ---                     +
    |                     | follow: false           +
    |                     | reblog: false           +
    |                     | favourite: false        +
    |                     | mention: false          +
    |                     | follow_request: true    +
    |                     | digest: true            +
    |                     |
  8 | interactions        | ---                     +
    |                     | must_be_follower: false +
    |                     | must_be_following: false+
    |                     |
  9 | default_privacy     | --- public              +
    |                     | ...                     +
    |                     |
 10 | boost_modal         | --- false               +
    |                     | ...                     +
    |                     |
 11 | delete_modal        | --- true                +
    |                     | ...                     +
    |                     |
 12 | auto_play_gif       | --- false               +
    |                     | ...                     +
    |                     |
(6 rows)
```

How does a record for that account looks?

And you can reset it by deleting some or all of those records, then default value will be used.

**Comment by Mnkai** [comment]
Hello, thanks for helping me.
I tried your query in my database, and query returned no result.

```
postgres=# SELECT var, value FROM settings JOIN users ON settings.thing_id = users.id WHERE settings.thing_type = 'User' AND users.account_id = 1;                          
(0 rows)                                                                                                                                                                    
                                                                                                                                                                            
postgres=# select * from accounts where id = 1;                                                                                                                             
-[ RECORD 1 ]-----------+-----------------------------------------------------------------                                                                                  
id                      | 1                                                                                                                                                 
username                | Mnkai_rin                                                                                                                                         
domain                  |                                                                                                                                                   
secret                  |                                                                                                                                                   
private_key             | -----BEGIN RSA PRIVATE KEY-----                                 +       
...
```

Maybe default value is corrupt? Other user (with working notification) has record with your query.

```
postgres=# SELECT var, value FROM settings JOIN users ON settings.thing_id = users.id WHERE settings.thing_type = 'User' AND users.account_id = 747;
-[ RECORD 1 ]-------------------
var   | auto_play_gif
value | --- true                +
      | ...                     +
      | 
-[ RECORD 2 ]-------------------
var   | boost_modal
value | --- false               +
      | ...                     +
      | 
-[ RECORD 3 ]-------------------
var   | default_privacy
value | --- public              +
      | ...                     +
      | 
-[ RECORD 4 ]-------------------
var   | interactions
value | ---                     +
      | must_be_follower: false +
      | must_be_following: false+
...
```

**Comment by unarist** [comment]
Default value is stored in `config/settings.yml`, but...

Could you try `rails r 'Rails.cache.clear'` command in the container?
For example, `docker-compose run --rm web rails r 'Rails.cache.clear'`.

**Comment by Mnkai** [comment]
Already tried once, but I did it again, just in case.
After clearing Ruby cache, I restarted Mastodon instance. But still no improvement.
I looked at the startup log, and one thing I have found somewhat error-like is this:
`web_1        | X-Accel-Mapping header missing`

And I saw some logs that resembles `rails r 'Rails.cache.clear'` output:
```
sidekiq_1    | Creating scope :cache_ids. Overwriting existing method Notification.cache_ids.
web_1        | Creating scope :cache_ids. Overwriting existing method Notification.cache_ids.
```

Also subsystems tried making group 'mastodon', but they were already there.
```
sidekiq_1    | Creating mastodon user (UID : 991 and GID : 991)...
sidekiq_1    | addgroup: group 'mastodon' in use
sidekiq_1    | Updating permissions...
web_1        | Creating mastodon user (UID : 991 and GID : 991)...
web_1        | addgroup: group 'mastodon' in use
web_1        | Updating permissions...
streaming_1  | Creating mastodon user (UID : 991 and GID : 991)...
streaming_1  | addgroup: group 'mastodon' in use
streaming_1  | Updating permissions...
```
Related folder should be `public`, so I will post `public` folder's permission information here.
```
[minori@mNetwork-Mastodon-Instance-Server public]$ ls -al
total 388
drwxr-xr-x  9 minori minori   4096 Jun 29 11:21 .
drwxr-xr-x 18 minori minori   4096 Jun 29 23:50 ..
-rw-r--r--  1 minori minori    990 Apr 20 10:44 500.html
-rw-r--r--  1 minori minori  14344 Apr 20 10:44 android-chrome-192x192.png
-rw-r--r--  1 minori minori   4217 Apr 20 10:44 apple-touch-icon.png
drwxr-xr-x  7    991    991   4096 Jun 30 00:16 assets
drwxr-xr-x  3 minori minori   4096 Apr 20 10:44 avatars
-rw-r--r--  1 minori minori    222 Apr 20 10:44 browserconfig.xml
drwxr-xr-x  2 minori minori 135168 Apr 20 10:44 emoji
-rw-r--r--  1 minori minori   9854 May  5 07:58 favicon-dev.ico
-rw-r--r--  1 minori minori    927 Apr 20 10:44 favicon.ico
drwxr-xr-x  3 minori minori   4096 Apr 20 10:44 headers
-rw-r--r--  1 minori minori    544 Apr 20 10:44 mask-icon.svg
-rw-r--r--  1 minori minori   6916 Apr 20 10:44 mstile-150x150.png
-rw-r--r--  1 minori minori 120305 Apr 20 10:44 oops.png
drwxr-xr-x  2    991    991  40960 Jun 29 11:48 packs
-rw-r--r--  1 minori minori    202 Apr 20 10:44 robots.txt
drwxr-xr-x  2 minori minori   4096 May 31 15:55 sounds
drwxr-xr-x  5    991    991   4096 Apr 20 23:36 system
```

**Comment by Mnkai** [comment]
OK, solved. I feel really stupid.
During update to 1.4.6, I manually solved git merge conflict of `config/settings.yml` file, and I think I may have pressed too much `d`'s while solving conflict with vim.
```
[minori@mNetwork-Mastodon-Instance-Server mastodon]$ git diff config/settings.yml
diff --git a/config/settings.yml b/config/settings.yml
index 7b78b6cd..427cc632 100644
--- a/config/settings.yml
+++ b/config/settings.yml
@@ -6,11 +6,10 @@
 #
 # For more information, see docs/Running-Mastodon/Administration-guide.md
 #
-defaults: &defaults
-  site_title: Mastodon
+  site_title: 'mNetwork Mastodon'
   site_description: ''
   site_extended_description: ''
-  site_contact_username: ''
+  site_contact_username: 'Minori Hiraoka'
   site_contact_email: ''
   open_registrations: true
   closed_registrations_message: ''
```
```
[minori@mNetwork-Mastodon-Instance-Server mastodon]$ vim config/settings.yml 
```
```
[minori@mNetwork-Mastodon-Instance-Server mastodon]$ git diff config/settings.yml
diff --git a/config/settings.yml b/config/settings.yml
index 7b78b6cd..86a12da0 100644
--- a/config/settings.yml
+++ b/config/settings.yml
@@ -7,10 +7,10 @@
 # For more information, see docs/Running-Mastodon/Administration-guide.md
 #
 defaults: &defaults
-  site_title: Mastodon
+  site_title: 'mNetwork Mastodon'
   site_description: ''
   site_extended_description: ''
-  site_contact_username: ''
+  site_contact_username: 'Minori Hiraoka'
   site_contact_email: ''
   open_registrations: true
   closed_registrations_message: ''
[minori@mNetwork-Mastodon-Instance-Server mastodon]$ 
```
It lacked `defaults: &defaults`, so accounts without explicit setting override from default were not able to function correctly. 
Thank you unarist, without you, I wouldn't have been able to find this mistake.

**Comment by Mnkai** [comment]
Since this problem derived from my mistake, I will now close this issue.
