### ISSUE TITLE
Can't follow accounts from other instances (error 500)

### ISSUE THREAD

**Issue by saschafoerster** [tootsuite/mastodon#6796]
Since the update to the latest version 2.3.1, I and others from my instance can't follow accounts from different instances. Everything works well, as long as I stay on Bonn.social. 

First I thought it could be related to the change of the SMTP-server, but the SMTP-server is now up and running again, the follow bug is persisting. 

On the browser I get the error message: HTTP2.0/500. 

The logfiles show this (2 examples): 

```
method=POST path=/api/v1/accounts/18921/follow format=html controller=Api::V1::AccountsController action=follow status=401 duration=390.53 view=0.00 db=72.98  
NoMethodError (undefined method `featured_collection_url=' for #<Account:0x000055869d967980>):
app/services/activitypub/process_account_service.rb:65:in `set_immediate_attributes!'
app/services/activitypub/process_account_service.rb:54:in `update_account'
app/services/activitypub/process_account_service.rb:24:in `block in call'
app/services/activitypub/process_account_service.rb:17:in `call'
app/services/resolve_account_service.rb:100:in `handle_activitypub'
app/services/resolve_account_service.rb:48:in `block in call'
app/services/resolve_account_service.rb:43:in `call'
app/services/follow_service.rb:12:in `call'
app/controllers/api/v1/accounts_controller.rb:16:in `follow'

```
```

method=POST path=/api/v1/accounts/15367/follow format=html controller=Api::V1::AccountsController action=follow status=401 duration=2040.69 view=0.00 db=3.40  
NoMethodError (undefined method `featured_collection_url=' for #<Account:0x000055869c2c80f8>):
app/services/activitypub/process_account_service.rb:65:in `set_immediate_attributes!'
app/services/activitypub/process_account_service.rb:54:in `update_account'
app/services/activitypub/process_account_service.rb:24:in `block in call'
app/services/activitypub/process_account_service.rb:17:in `call'
app/services/resolve_account_service.rb:100:in `handle_activitypub'
app/services/resolve_account_service.rb:48:in `block in call'
app/services/resolve_account_service.rb:43:in `call'
app/services/follow_service.rb:12:in `call'
app/controllers/api/v1/accounts_controller.rb:16:in `follow'
[493dcd91-194c-4333-b316-8407ebf3957b] [active_model_serializers] Rendered ActiveModel::Serializer::CollectionSerializer with ActiveModelSerializers::Adapter::Attributes (0.14ms)
[493dcd91-194c-4333-b316-8407ebf3957b] method=GET path=/api/v1/accounts/5478/statuses format=html controller=Api::V1::Accounts::StatusesController action=index status=200 duration=25.62 view=0.94 db=6.14
```
Would be great if I could get some help debugging, because I am not shure, if this is my fault or a bug. 

* * * *

- [x ] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by agirisan** [comment]
also experiencing this after 2.3.1 upgrade
happens when following users on older instances as well as instances on 2.3.1

**Comment by nightpool** [comment]
```
NoMethodError (undefined method `featured_collection_url=' for #<Account:0x000055869c2c80f8>):
```

this sounds like you updated the code without running the db migrations.

can you post the results of executing `RAILS_ENV=production bundle exec rails db:migrate` ?

**Comment by agirisan** [comment]
fixed in my case - apparently forgot to run the migrations

**Comment by saschafoerster** [comment]
```

Migrating to MoreFasterIndexOnNotifications (20171226094803)
== 20171226094803 MoreFasterIndexOnNotifications: migrating ===================
-- add_index(:notifications, [:account_id, :id], {:order=>{:id=>:desc}, :algorithm=>:concurrently})
rake aborted!
StandardError: An error has occurred, all later migrations canceled:

Index name 'index_notifications_on_account_id_and_id' on table 'notifications' already exists
/mastodon/vendor/bundle/ruby/2.5.0/gems/activerecord-5.1.4/lib/active_record/connection_adapters/abstract/schema_statements.rb:1156:in `add_index_options'
/mastodon/vendor/bundle/ruby/2.5.0/gems/activerecord-5.1.4/lib/active_record/connection_adapters/postgresql/schema_statements.rb:481:in `add_index'
/mastodon/vendor/bundle/ruby/2.5.0/gems/activerecord-5.1.4/lib/active_record/migration.rb:849:in `block in method_missing'
/mastodon/vendor/bundle/ruby/2.5.0/gems/activerecord-5.1.4/lib/active_record/migration.rb:818:in `block in say_with_time'
/mastodon/vendor/bundle/ruby/2.5.0/gems/activerecord-5.1.4/lib/active_record/migration.rb:818:in `say_with_time'
/mastodon/vendor/bundle/ruby/2.5.0/gems/activerecord-5.1.4/lib/active_record/migration.rb:838:in `method_missing'
/mastodon/vendor/bundle/ruby/2.5.0/gems/strong_migrations-0.1.9/lib/strong_migrations/migration.rb:63:in `method_missing'
/mastodon/db/migrate/20171226094803_more_faster_index_on_notifications.rb:5:in `change'
/mastodon/vendor/bundle/ruby/2.5.0/gems/activerecord-5.1.4/lib/active_record/migration.rb:792:in `exec_migration'
/mastodon/vendor/bundle/ruby/2.5.0/gems/activerecord-5.1.4/lib/active_record/migration.rb:776:in `block (2 levels) in migrate'
/mastodon/vendor/bundle/ruby/2.5.0/gems/activerecord-5.1.4/lib/active_record/migration.rb:775:in `block in migrate'
/mastodon/vendor/bundle/ruby/2.5.0/gems/activerecord-5.1.4/lib/active_record/connection_adapters/abstract/connection_pool.rb:408:in `with_connection'
/mastodon/vendor/bundle/ruby/2.5.0/gems/activerecord-5.1.4/lib/active_record/migration.rb:774:in `migrate'
/mastodon/vendor/bundle/ruby/2.5.0/gems/strong_migrations-0.1.9/lib/strong_migrations/migration.rb:13:in `migrate'
/mastodon/vendor/bundle/ruby/2.5.0/gems/chewy-5.0.0/lib/chewy/railtie.rb:37:in `block in migrate'
/mastodon/vendor/bundle/ruby/2.5.0/gems/chewy-5.0.0/lib/chewy/strategy.rb:70:in `wrap'
/mastodon/vendor/bundle/ruby/2.5.0/gems/chewy-5.0.0/lib/chewy.rb:201:in `strategy'
/mastodon/vendor/bundle/ruby/2.5.0/gems/chewy-5.0.0/lib/chewy/railtie.rb:37:in `migrate'
/mastodon/vendor/bundle/ruby/2.5.0/gems/activerecord-5.1.4/lib/active_record/migration.rb:953:in `migrate'
/mastodon/vendor/bundle/ruby/2.5.0/gems/activerecord-5.1.4/lib/active_record/migration.rb:1230:in `block in execute_migration_in_transaction'
/mastodon/vendor/bundle/ruby/2.5.0/gems/activerecord-5.1.4/lib/active_record/migration.rb:1300:in `ddl_transaction'
/mastodon/vendor/bundle/ruby/2.5.0/gems/activerecord-5.1.4/lib/active_record/migration.rb:1229:in `execute_migration_in_transaction'
/mastodon/vendor/bundle/ruby/2.5.0/gems/activerecord-5.1.4/lib/active_record/migration.rb:1201:in `block in migrate_without_lock'
/mastodon/vendor/bundle/ruby/2.5.0/gems/activerecord-5.1.4/lib/active_record/migration.rb:1200:in `each'
/mastodon/vendor/bundle/ruby/2.5.0/gems/activerecord-5.1.4/lib/active_record/migration.rb:1200:in `migrate_without_lock'
/mastodon/vendor/bundle/ruby/2.5.0/gems/activerecord-5.1.4/lib/active_record/migration.rb:1148:in `block in migrate'
/mastodon/vendor/bundle/ruby/2.5.0/gems/activerecord-5.1.4/lib/active_record/migration.rb:1317:in `with_advisory_lock'
/mastodon/vendor/bundle/ruby/2.5.0/gems/activerecord-5.1.4/lib/active_record/migration.rb:1148:in `migrate'
/mastodon/vendor/bundle/ruby/2.5.0/gems/chewy-5.0.0/lib/chewy/railtie.rb:37:in `block in migrate'
/mastodon/vendor/bundle/ruby/2.5.0/gems/chewy-5.0.0/lib/chewy/strategy.rb:70:in `wrap'
/mastodon/vendor/bundle/ruby/2.5.0/gems/chewy-5.0.0/lib/chewy.rb:201:in `strategy'
/mastodon/vendor/bundle/ruby/2.5.0/gems/chewy-5.0.0/lib/chewy/railtie.rb:37:in `migrate'
/mastodon/vendor/bundle/ruby/2.5.0/gems/activerecord-5.1.4/lib/active_record/migration.rb:1007:in `up'
/mastodon/vendor/bundle/ruby/2.5.0/gems/activerecord-5.1.4/lib/active_record/migration.rb:985:in `migrate'
/mastodon/vendor/bundle/ruby/2.5.0/gems/activerecord-5.1.4/lib/active_record/tasks/database_tasks.rb:171:in `migrate'
/mastodon/vendor/bundle/ruby/2.5.0/gems/activerecord-5.1.4/lib/active_record/railties/databases.rake:58:in `block (2 levels) in <top (required)>'
/mastodon/vendor/bundle/ruby/2.5.0/gems/rake-12.3.0/exe/rake:27:in `<top (required)>'

Caused by:
ArgumentError: Index name 'index_notifications_on_account_id_and_id' on table 'notifications' already exists
/mastodon/vendor/bundle/ruby/2.5.0/gems/activerecord-5.1.4/lib/active_record/connection_adapters/abstract/schema_statements.rb:1156:in `add_index_options'
/mastodon/vendor/bundle/ruby/2.5.0/gems/activerecord-5.1.4/lib/active_record/connection_adapters/postgresql/schema_statements.rb:481:in `add_index'
/mastodon/vendor/bundle/ruby/2.5.0/gems/activerecord-5.1.4/lib/active_record/migration.rb:849:in `block in method_missing'
/mastodon/vendor/bundle/ruby/2.5.0/gems/activerecord-5.1.4/lib/active_record/migration.rb:818:in `block in say_with_time'
/mastodon/vendor/bundle/ruby/2.5.0/gems/activerecord-5.1.4/lib/active_record/migration.rb:818:in `say_with_time'
/mastodon/vendor/bundle/ruby/2.5.0/gems/activerecord-5.1.4/lib/active_record/migration.rb:838:in `method_missing'
/mastodon/vendor/bundle/ruby/2.5.0/gems/strong_migrations-0.1.9/lib/strong_migrations/migration.rb:63:in `method_missing'
/mastodon/db/migrate/20171226094803_more_faster_index_on_notifications.rb:5:in `change'
/mastodon/vendor/bundle/ruby/2.5.0/gems/activerecord-5.1.4/lib/active_record/migration.rb:792:in `exec_migration'
/mastodon/vendor/bundle/ruby/2.5.0/gems/activerecord-5.1.4/lib/active_record/migration.rb:776:in `block (2 levels) in migrate'
/mastodon/vendor/bundle/ruby/2.5.0/gems/activerecord-5.1.4/lib/active_record/migration.rb:775:in `block in migrate'
/mastodon/vendor/bundle/ruby/2.5.0/gems/activerecord-5.1.4/lib/active_record/connection_adapters/abstract/connection_pool.rb:408:in `with_connection'
/mastodon/vendor/bundle/ruby/2.5.0/gems/activerecord-5.1.4/lib/active_record/migration.rb:774:in `migrate'
/mastodon/vendor/bundle/ruby/2.5.0/gems/strong_migrations-0.1.9/lib/strong_migrations/migration.rb:13:in `migrate'
/mastodon/vendor/bundle/ruby/2.5.0/gems/chewy-5.0.0/lib/chewy/railtie.rb:37:in `block in migrate'
/mastodon/vendor/bundle/ruby/2.5.0/gems/chewy-5.0.0/lib/chewy/strategy.rb:70:in `wrap'
/mastodon/vendor/bundle/ruby/2.5.0/gems/chewy-5.0.0/lib/chewy.rb:201:in `strategy'
/mastodon/vendor/bundle/ruby/2.5.0/gems/chewy-5.0.0/lib/chewy/railtie.rb:37:in `migrate'
/mastodon/vendor/bundle/ruby/2.5.0/gems/activerecord-5.1.4/lib/active_record/migration.rb:953:in `migrate'
/mastodon/vendor/bundle/ruby/2.5.0/gems/activerecord-5.1.4/lib/active_record/migration.rb:1230:in `block in execute_migration_in_transaction'
/mastodon/vendor/bundle/ruby/2.5.0/gems/activerecord-5.1.4/lib/active_record/migration.rb:1300:in `ddl_transaction'
/mastodon/vendor/bundle/ruby/2.5.0/gems/activerecord-5.1.4/lib/active_record/migration.rb:1229:in `execute_migration_in_transaction'
/mastodon/vendor/bundle/ruby/2.5.0/gems/activerecord-5.1.4/lib/active_record/migration.rb:1201:in `block in migrate_without_lock'
/mastodon/vendor/bundle/ruby/2.5.0/gems/activerecord-5.1.4/lib/active_record/migration.rb:1200:in `each'
/mastodon/vendor/bundle/ruby/2.5.0/gems/activerecord-5.1.4/lib/active_record/migration.rb:1200:in `migrate_without_lock'
/mastodon/vendor/bundle/ruby/2.5.0/gems/activerecord-5.1.4/lib/active_record/migration.rb:1148:in `block in migrate'
/mastodon/vendor/bundle/ruby/2.5.0/gems/activerecord-5.1.4/lib/active_record/migration.rb:1317:in `with_advisory_lock'
/mastodon/vendor/bundle/ruby/2.5.0/gems/activerecord-5.1.4/lib/active_record/migration.rb:1148:in `migrate'
/mastodon/vendor/bundle/ruby/2.5.0/gems/chewy-5.0.0/lib/chewy/railtie.rb:37:in `block in migrate'
/mastodon/vendor/bundle/ruby/2.5.0/gems/chewy-5.0.0/lib/chewy/strategy.rb:70:in `wrap'
/mastodon/vendor/bundle/ruby/2.5.0/gems/chewy-5.0.0/lib/chewy.rb:201:in `strategy'
/mastodon/vendor/bundle/ruby/2.5.0/gems/chewy-5.0.0/lib/chewy/railtie.rb:37:in `migrate'
/mastodon/vendor/bundle/ruby/2.5.0/gems/activerecord-5.1.4/lib/active_record/migration.rb:1007:in `up'
/mastodon/vendor/bundle/ruby/2.5.0/gems/activerecord-5.1.4/lib/active_record/migration.rb:985:in `migrate'
/mastodon/vendor/bundle/ruby/2.5.0/gems/activerecord-5.1.4/lib/active_record/tasks/database_tasks.rb:171:in `migrate'
/mastodon/vendor/bundle/ruby/2.5.0/gems/activerecord-5.1.4/lib/active_record/railties/databases.rake:58:in `block (2 levels) in <top (required)>'
/mastodon/vendor/bundle/ruby/2.5.0/gems/rake-12.3.0/exe/rake:27:in `<top (required)>'
Tasks: TOP => db:migrate
(See full trace by running task with --trace)
```

**Comment by saschafoerster** [comment]
Indeed I didn't run "rails db migrate", because I upgraded from v2.3 and in the release notes it didn't mention the need for migration: 
https://github.com/tootsuite/mastodon/releases/tag/v2.3.1
But still, after a fresh build and start, it stays the same... follows don't work. 

By the way: I'm using the docker-installation, if that helps.

**Comment by jebuskrust** [comment]
Interesting, Looks like that migration already ran..  If you're able to connect to the postgresql instances using psql you can skip this migration by connecting to the instance database and inserting the version of the migration into the schema_migrations table.. like below.


```
postgres@localhost:/home/secure$ psql
psql (9.6.6)
Type "help" for help.
postgres=#

postgres=# \c mastodon_production
You are now connected to database "mastodon_production" as user "postgres".
mastodon_production=# INSERT into schema_migrations(version) VALUES ('20171226094803');

```
Then rerun your db migrate command again., and it should skip that one migration that failed.. 

Cheers.

**Comment by jebuskrust** [comment]
Oh darn. You should have put that in a screen. It should be good hopefully. If not, we should be able to figure something out.

**Comment by saschafoerster** [comment]
So, git fetch is on the newest version 2.3.3.
When I run db:migrate, I get this:

```
root@sfvm01:/home/mastodon# docker-compose run --rm web rake db:migrate
Migrating to AddIndexOnStatusesForApiV1AccountsAccountIdStatuses (20180106000232)
== 20180106000232 AddIndexOnStatusesForApiV1AccountsAccountIdStatuses: migrating 
-- add_index(:statuses, [:account_id, :id, :visibility, :updated_at], {:order=>{:id=>:desc}, :algorithm=>:concurrently, :name=>:index_statuses_20180106})
rake aborted!
StandardError: An error has occurred, all later migrations canceled:
....
```

If I look into /home/mastodon/db/ I see the following migrations (just displaying the last ones):

```

root@sfvm01:/home/mastodon# ll /home/mastodon/db/migrate/
insgesamt 608
....
-rw-r--r-- 1 root root  237 Dez 16 21:37 20171212195226_remove_duplicate_indexes_in_lists.rb
-rw-r--r-- 1 root root  315 Feb  5 23:59 20171226094803_more_faster_index_on_notifications.rb
-rw-r--r-- 1 root root  389 Feb  6 20:40 20180106000232_add_index_on_statuses_for_api_v1_accounts_account_id_statuses.rb
-rw-r--r-- 1 root root  144 Mär  9 23:29 20180109143959_add_remember_token_to_users.rb
-rw-r--r-- 1 root root  301 Mär  9 23:29 20180204034416_create_identities.rb
-rw-r--r-- 1 root root  187 Mär  9 23:29 20180206000000_change_user_id_nonnullable.rb
-rw-r--r-- 1 root root  279 Mär  9 23:29 20180211015820_create_backups.rb
-rw-r--r-- 1 root root  155 Mär  9 23:29 20180304013859_add_featured_collection_url_to_accounts.rb
```

I am not used to postgres, so I would be glad, if you could help me with the exact commands.. 
I tried this (successfully):

```
postgres=# \l
postgres=# \c postgres
postgres=# \dt
postgres=# SELECT * from schema_migrations;
    version     
----------------
 20160220174730
 20160220211917
 20160221003140
 20160221003621
 20160222122600
 20160222143943
 20160223162837
 20160223164502
 20160223165723
 20160223165855
 20160223171800
 20160224223247
 20160227230233
 20160305115639
 20160306172223
 20160312193225
 20160314164231
 20160316103650
 20160322193748
 20160325130944
 20160826155805
 20160905150353
 20160919221059
 20160920003904
 20160926213048
 20161003142332
 20161003145426
 20161006213403
 20161009120834
 20161027172456
 20161104173623
 20161105130633
 20161116162355
 20161119211120
 20161122163057
 20161123093447
 20161128103007
 20161130142058
 20161130185319
 20161202132159
 20161203164520
 20161205214545
 20161221152630
 20161222201034
 20161222204147
 20170105224407
 20170109120109
 20170112154826
 20170114194937
 20170114203041
 20170119214911
 20170123162658
 20170123203248
 20170125145934
 20170127165745
 20170129000348
 20170205175257
 20170209184350
 20170214110202
 20170217012631
 20170301222600
 20170303212857
 20170304202101
 20170317193015
 20170318214217
 20170322021028
 20170322143850
 20170322162804
 20170330021336
 20170330163835
 20170330164118
 20170403172249
 20170405112956
 20170406215816
 20170409170753
 20170414080609
 20170414132105
 20170418160728
 20170424112722
 20170425131920
 20170425202925
 20170423005413
 20170424003227
 20170506235850
 20170507000211
 20170507141759
 20170508230434
 20170516072309
 20170520145338
 20170601210557
 20170604144747
 20170606113804
 20170609145826
 20170610000000
 20170623152212
 20170624134742
 20170625140443
 20170711225116
 20170713112503
 20170713175513
 20170713190709
 20170714184731
 20170718211102
 20170720000000
 20170427011934
 20170823162448
 20170824103029
 20170829215220
 20170901141119
 20170901142658
 20170905044538
 20170905165803
 20170913000752
 20170917153509
 20170918125918
 20170920024819
 20170920032311
 20170924022025
 20170927215609
 20170928082043
 20171005102658
 20171005171936
 20171006142024
 20171010023049
 20171010025614
 20170716191202
 20171020084748
 20171028221157
 20171107143332
 20171107143624
 20171109012327
 20171114080328
 20171114231651
 20171116161857
 20171118012443
 20171119172437
 20171122120436
 20171125024930
 20171125031751
 20171125185353
 20171125190735
 20171129172043
 20171130000000
 20171201000000
 20171212195226
 20171226094803
(146 rows)
```
So far: now I will try it the missing migrations manuelle with the information from /home/mastodon/db.
Whish my luck! :)

**Comment by saschafoerster** [comment]
I now tried to add the failing migration manually into the database:

`postgres=# INSERT into schema_migrations(version) VALUES ('20180106000232');`

After that, the other migrations just went on! 

```
root@sfvm01:/home/mastodon# docker-compose run --rm web rake db:migrate
Migrating to AddRememberTokenToUsers (20180109143959)
== 20180109143959 AddRememberTokenToUsers: migrating ==========================
-- add_column(:users, :remember_token, :string, {:null=>true})
   -> 0.2132s
== 20180109143959 AddRememberTokenToUsers: migrated (0.2144s) =================

Migrating to CreateIdentities (20180204034416)
== 20180204034416 CreateIdentities: migrating =================================
-- adapter_name()
   -> 0.0000s
-- adapter_name()
   -> 0.0000s
-- create_table(:identities, {:id=>:integer})
   -> 0.6488s
== 20180204034416 CreateIdentities: migrated (0.6491s) ========================

Migrating to ChangeUserIdNonnullable (20180206000000)
== 20180206000000 ChangeUserIdNonnullable: migrating ==========================
-- change_column_null(:invites, :user_id, false)
   -> 0.0007s
-- change_column_null(:web_settings, :user_id, false)
   -> 0.1912s
== 20180206000000 ChangeUserIdNonnullable: migrated (0.1922s) =================

Migrating to CreateBackups (20180211015820)
== 20180211015820 CreateBackups: migrating ====================================
-- create_table(:backups)
   -> 0.0568s
== 20180211015820 CreateBackups: migrated (0.0569s) ===========================

Migrating to AddFeaturedCollectionUrlToAccounts (20180304013859)
== 20180304013859 AddFeaturedCollectionUrlToAccounts: migrating ===============
-- add_column(:accounts, :featured_collection_url, :string)
   -> 0.0011s
== 20180304013859 AddFeaturedCollectionUrlToAccounts: migrated (0.0012s) ======
```
I hope the missing or duplicated migration 20180106000232 will not cause side-effects. I tried to enter the commands in /home/mastodon/db/20180106000232.rb into psql to check but without success.

**Comment by redtachyons** [comment]
What about the original issue, is it resolved after running the migration?

**Comment by saschafoerster** [comment]
As far as I can see everything works. Thanks for the help, @jebuskrust and @nightpool!

**Comment by nolanlawson** [comment]
I'm apparently running into exactly this same issue after upgrading from 2.3.1 to 2.3.3. Users are unable to follow remote accounts, plenty of Sidekiq jobs are failing, and the Sidekiq logs say:

```
 {"context":"Job raised exception","job":{"class":"ActivityPub::SynchronizeFeaturedCollectionWorker","args":[15043],"retry":true,"queue":"pull","jid":"1bec9a5c614be57d12caeda3","created_at":1522547595.4297228,"enqueued_at":1522663440.9521203,"error_message":"undefined method `featured_collection_url' for nil:NilClass","error_class":"NoMethodError","failed_at":1522565513.8379936,"retry_count":4,"retried_at"
:1522663125.9072883},"jobstr":"{\"class\":\"ActivityPub::SynchronizeFeaturedCollectionWorker
\",\"args\":[15043],\"retry\":true,\"queue\":\"pull\",\"jid\":\"1bec9a5c614be57d12caeda3\",\"created_at
\":1522547595.4297228,\"enqueued_at\":1522663440.9521203,\"error_message\":\"undefined 
method `featured_collection_url' for nil:NilClass\",\"error_class\":\"NoMethodError\",\"failed_at
\":1522565513.8379936,\"retry_count\":4,\"retried_at\":1522663125.9072883}"}
```

I checked in `db/migrate` and the last migration listed is `20180304013859_add_featured_collection_url_to_accounts.rb`. Unfortunately when I run `db:migrate` nothing happens, so I'm not sure how to fix this. :confused:

When I upgraded from 2.3.1 to 2.3.3, I undoubtedly ran `db:migrate` (because that's what my scripts do), but unfortunately I didn't save the output so I have no idea if there was a failure or not. The `db:migrate` command must have exited with a zero status, though, because my entire script would have failed otherwise.

**Comment by nolanlawson** [comment]
I should mention that I'm still running Ruby 2.4.2, not sure if that would have an impact.

**Comment by nolanlawson** [comment]
Actually it could be that my issue is different; it looks like `20180304013859` is the latest db migration for 2.3.3?
