### ISSUE TITLE
Blank/grey site after updating to 2.4.0

### ISSUE THREAD

**Issue by kkretsch** [tootsuite/mastodon#7596]
I updated from 2.3.3 to 2.4.0 for a standalone installation.
The anonymous front page still works, as does the sidekiq in my browser.
But if I login the side gets blank/grey no content visible.
The console within my firefox gives that error:

Error
​columnNumber: 653197
​fileName: "https://m.kretschmann.social/packs/common-ee4fe4bdb288f72c6d7f.js"
​lineNumber: 1
​message: "Cannot find module \"exif-js\""

Normal API requests seem to pass through my access log still. Just the gui is crashed.

I did try to recompile the assets. No error shown but no success either.

* * * *

- [X] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [X] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by maop** [comment]
Hello, i just had this error too, but it's fixed now...

What happened is that i ran assets:precompile without executing "yarn install" first... so there was an error i didnt notice and when i restarted mastodon-web.service site went blank with the same error in the javascript console as mentioned above.

I went back to `yarn install` , then `assets:precompile`, `restart mastodon-web`, and nothing... still blank site... then i re-run `$ yarn install --force` , then `assets:precompile` again (this time it did compile everything again) and `restart mastodon-web`... _et voilá_ site changed from 'blank' to "Error 500" hehe, but just a quick CTRL-R (reload page) and everything is working just fine now.

Hope it helps
Hope i explain everything good enough, sorry for my english.

**Comment by kkretsch** [comment]
I had problems with yarn before too. So that might be the very same error. I'll try that "--force" parameter later and will report back.
