### ISSUE TITLE
NoMethodError: undefined method 'n='

### ISSUE THREAD

**Issue by Luclu7** [tootsuite/mastodon#3628]
Since I upgraded to v1.4.1, I have a lot of sidekiq retry tasks which is like:
`NoMethodError: undefined method 'n=' for #<OpenSSL::PKey::RSA:0xXXXXXXXXXXXXXX> Did you mean? n`.
They spawn very frequently (~20/minute). (the `RSA:0xXXXXXXXXXXXXXX` is like `RSA:0x00562f28e20df8`)

* * * *

- [X] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [X] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by Gargron** [comment]
You should be on Ruby 2.4.1, or are you on Ruby 2.3.1?

**Comment by Luclu7** [comment]
Ooops, my bad, rbenv gave back ruby 2.3 as the global.
