### ISSUE TITLE
Notifications fail to load

### ISSUE THREAD

**Issue by riking** [tootsuite/mastodon#1491]
Bad commit https://github.com/tootsuite/mastodon/commit/12f72e1740cd91929419c82c6b782393e306994c

```
application-40ef2e74c5e2f7d364d4364f187e18e4b1cd3a785debb8a00a1532ba1e37b483.js:39
TypeError: status.getIn is not a function
    at Object.render (application-40ef2e74c5e2f7d364d4364f187e18e4b1cd3a785debb8a00a1532ba1e37b483.js:30)
    at ReactCompositeComponentWrapper._renderValidatedComponentWithoutOwnerOrContext (application-40ef2e74c5e2f7d364d4364f187e18e4b1cd3a785debb8a00a1532ba1e37b483.js:702)
    at ReactCompositeComponentWrapper._renderValidatedComponent (application-40ef2e74c5e2f7d364d4364f187e18e4b1cd3a785debb8a00a1532ba1e37b483.js:702)
    at ReactCompositeComponentWrapper.performInitialMount (application-40ef2e74c5e2f7d364d4364f187e18e4b1cd3a785debb8a00a1532ba1e37b483.js:702)
    at ReactCompositeComponentWrapper.mountComponent (application-40ef2e74c5e2f7d364d4364f187e18e4b1cd3a785debb8a00a1532ba1e37b483.js:702)
    at Object.mountComponent (application-40ef2e74c5e2f7d364d4364f187e18e4b1cd3a785debb8a00a1532ba1e37b483.js:1110)
    at ReactCompositeComponentWrapper.performInitialMount (application-40ef2e74c5e2f7d364d4364f187e18e4b1cd3a785debb8a00a1532ba1e37b483.js:702)
    at ReactCompositeComponentWrapper.mountComponent (application-40ef2e74c5e2f7d364d4364f187e18e4b1cd3a785debb8a00a1532ba1e37b483.js:702)
    at Object.mountComponent (application-40ef2e74c5e2f7d364d4364f187e18e4b1cd3a785debb8a00a1532ba1e37b483.js:1110)
    at ReactCompositeComponentWrapper.performInitialMount (application-40ef2e74c5e2f7d364d4364f187e18e4b1cd3a785debb8a00a1532ba1e37b483.js:702)
(anonymous) @ application-40ef2e74c5e2f7d364d4364f187e18e4b1cd3a785debb8a00a1532ba1e37b483.js:39
```

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by wxcafe** [comment]
![screenshot from 2017-04-11 01-57-15](https://cloud.githubusercontent.com/assets/3009327/24887467/424c62c4-1e5c-11e7-9e63-0b871f959894.png) Part of the nginx log that might be related, and

![screenshot from 2017-04-11 01-37-59](https://cloud.githubusercontent.com/assets/3009327/24887484/5abec590-1e5c-11e7-93eb-2bcc0a0ae54d.png)

console log in firefox.

Seems like other people have the same problem https://ohai.su/users/lutoma/updates/146

**Comment by wxcafe** [comment]
This was following upgrading to master from v1.1.1. I basically followed the production guide: 
- `services stop`
- `git pull`
- `rbenv install 2.4.1`
- `gem install bundler`
- `bundle install`
- `RAILS_ENV=production bundle exec rails db:migrate`
- `RAILS_ENV=production bundle exec rails assets:precompile`
- `services start`

**Comment by mjankowski** [comment]
Possibly related commit (which is after 1.1.1) - https://github.com/tootsuite/mastodon/commit/12f72e1740cd91929419c82c6b782393e306994c

**Comment by wxcafe** [comment]
Rerolling to v1.1.1 AND downgrading the assets fixes it (I'm dumb)

**Comment by Gargron** [comment]
Possibly introduced in 2810013b933bceb2a7c1d1b8b10d2714c39d1e15 (unlikely that it's 12f72e1)

**Comment by riking** [comment]
Notifications were still streaming, and working in the Android app.

And it seems I accidentally hid it, but the actual error is `TypeError: status.getIn is not a function` - I'm not sure how it could be anything else?

**Comment by Fastidious** [comment]
Same happening to my instance (“Ops! An unexpected error occurred.” message). Notifications are blank. Running latest master.

**Comment by Wonderfall** [comment]
Reverted to 0687ab8ae3c2573ba2aa1d37f62e3583d0c7ab01 and it works again.

**Comment by riking** [comment]
looking over my draft of an integration test vv, Follow notifications don't have a `status` do they?

There wasn't any other access of the `status` property there before that commit.

**Comment by Fusl** [comment]
@riking That seems to be the case. My notifications are loading until I scroll down to where the latest follow notification is at which point it stops loading and fails with the error `TypeError: status.getIn is not a function`.

**Comment by Fastidious** [comment]
Could someone post the temporary fix for this? Will a `git revert 0687ab8` be the way to go? Please advise.

**Comment by wxcafe** [comment]
@Fastidious `git checkout 0687ab8`, `RAILS_ENV=production bundle exec rails db:migrate`, `RAILS_ENV=production bundle exec rails assets:precompile`, `systemctl restart 'mastodon-*'`

**Comment by Fastidious** [comment]
@wxcafe I am on docker. Doing:

- `git checkout 0687ab8`
- `docker-compose run --rm web rails db:migrate`
- `docker-compose run --rm web rails assets:precompile`
- `docker-compose stop`
- `docker-compose up -d`

Will not fix the problem. Am I missing something?

**Comment by Gargron** [comment]
I found the source of the issue, preparing a PR.

**Comment by ericblade** [comment]
fwiw, i'm only seeing it when i attempt to search something.  will check out the fix.

**Comment by ericblade** [comment]
appears to be fixed with that commit
