### ISSUE TITLE
`rails assets:precompile` error when upgrade to 2.9.3 from 2.9.2

### ISSUE THREAD

**Issue by mfa777** [tootsuite/mastodon#11531]
Non-Docker version

```
$ bundle install
...
Bundle complete! 117 Gemfile dependencies, 197 gems now installed.
Gems in the groups development and test were not installed.
Bundled gems are installed into `./vendor/bundle`
```

```
$ RAILS_ENV=production bundle exec rails assets:precompile
yarn install v1.17.3
[1/6] Validating package.json...
[2/6] Resolving packages...
[3/6] Fetching packages...
info fsevents@1.2.9: The platform "linux" is incompatible with this module.
info "fsevents@1.2.9" is an optional dependency and failed compatibility check. Excluding it from in
stallation.
[4/6] Linking dependencies...
warning " > react-redux-loading-bar@4.0.8" has incorrect peer dependency "react-redux@^3.0.0 || ^4.0
.0 || ^5.0.0".
[5/6] Building fresh packages...
[6/6] Cleaning modules...
Done in 25.97s.
Compiling…
Compilation failed:
/home/mastodon/live/node_modules/webpack-cli/bin/cli.js:93
                                throw err;
                                ^

Error: Cannot find module '../lib/install/config/webpacker.yml'
```

I can't see this folder `../lib/install/` in my root path.

**Comment by angristan** [comment]
Maybe this can help: https://github.com/rails/webpacker/issues/1082
