### ISSUE TITLE
Notification column stopped working, assets not available

### ISSUE THREAD

**Issue by mkody** [tootsuite/mastodon#1521]
Pulled master (11898a6461c7a2261255b5a8f82ecb4181ae509d) and the notification column stopped working.  
I get a `Oops!An unexpected error occurred.` notification.

Here's what the javascript consoles says:
```
application-47f80b9….js:39 TypeError: status.getIn is not a function
    at Object.render (application-47f80b9….js:30)
    at ReactCompositeComponentWrapper._renderValidatedComponentWithoutOwnerOrContext (application-47f80b9….js:702)
    at ReactCompositeComponentWrapper._renderValidatedComponent (application-47f80b9….js:702)
    at ReactCompositeComponentWrapper.performInitialMount (application-47f80b9….js:702)
    at ReactCompositeComponentWrapper.mountComponent (application-47f80b9….js:702)
    at Object.mountComponent (application-47f80b9….js:1110)
    at ReactCompositeComponentWrapper.performInitialMount (application-47f80b9….js:702)
    at ReactCompositeComponentWrapper.mountComponent (application-47f80b9….js:702)
    at Object.mountComponent (application-47f80b9….js:1110)
    at ReactCompositeComponentWrapper.performInitialMount (application-47f80b9….js:702)

application-47f80b9….js:30 Uncaught (in promise) TypeError: status.getIn is not a function
    at Object.render (application-47f80b9….js:30)
    at ReactCompositeComponentWrapper._renderValidatedComponentWithoutOwnerOrContext (application-47f80b9….js:702)
    at ReactCompositeComponentWrapper._renderValidatedComponent (application-47f80b9….js:702)
    at ReactCompositeComponentWrapper.performInitialMount (application-47f80b9….js:702)
    at ReactCompositeComponentWrapper.mountComponent (application-47f80b9….js:702)
    at Object.mountComponent (application-47f80b9….js:1110)
    at ReactCompositeComponentWrapper.performInitialMount (application-47f80b9….js:702)
    at ReactCompositeComponentWrapper.mountComponent (application-47f80b9….js:702)
    at Object.mountComponent (application-47f80b9….js:1110)
    at ReactCompositeComponentWrapper.performInitialMount (application-47f80b9….js:702)
```

Also, some assets are throwing 404s. Same thing with pictures that I use in `custom.scss`  (logo.png) that doesn't get referenced properly after pre-compiling.
```
application-47f80b9….js:31 GET https://im-in.space/system/accounts/avatars/000/000/002/static/b8f811a330e64060.png?1491401122 404 (Not Found)
```

I tried that [with my edits](https://github.com/tootsuite/mastodon/compare/master...im-in-space:im-in.space) and with vanilla Mastodon

* * * *

- [X] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by mkody** [comment]
This problem was introduced with 12f72e1740cd91929419c82c6b782393e306994c

**Comment by wxcafe** [comment]
duplicate of #1491, closing

**Comment by mkody** [comment]
Huh, what the hell. It doesn't appear in the issue list for me.
Sorry, I guess.
