### ISSUE TITLE
Timelines not working after updating to docker 2.5.0rc1

### ISSUE THREAD

**Issue by csos95** [tootsuite/mastodon#8492]
### The problem:
After updating my prebuilt image docker install to v2.5.0rc1 only the federated and local timeline load statuses, my home and list timelines are all empty.
The federated timeline also isn't loading new toots, just showing existing ones.
If I go to the profile of someone I follow all of their previous toots from before the upgrade load fine.

### Upgrade steps:
- I followed the docker upgrade steps listed in the [release notes](https://github.com/tootsuite/mastodon/releases/tag/v2.5.0rc1).

### Things I've tried:
- `docker-compose down && docker-compose up -d`
- checkout v2.5.0rc1 again and try with the self-built image setup

### Errors found:
Sidekiq is showing lots of errors that appear to start at an undefined method for reblogs_count on statuses.
Nothing else appears to be throwing errors and all the api requests are successful.
```
2018-08-27T22:51:46.849Z 7 TID-gpxk1e0sr DistributionWorker JID-c03e221c507a6f3fa84f4590 INFO: start
2018-08-27T22:51:46.881Z 7 TID-gpxk1e0sr DistributionWorker JID-c03e221c507a6f3fa84f4590 INFO: fail: 0.032 sec
2018-08-27T22:51:46.881Z 7 TID-gpxk1e0sr WARN: {"context":"Job raised exception","job":{"class":"DistributionWorker","args":[100624626362482119],"retry":true,"queue":"default","jid":"c03e221c507a6f3fa84f4590","created_at":1535409948.1974733,"enqueued_at":1535410306.8475788,"error_message":"undefined method `reblogs_count' for #<Status:0x000055cd34a5c0d8>\nDid you mean?  reblogs","error_class":"NoMethodError","failed_at":1535409948.2260487,"retry_count":3,"retried_at":1535410096.6493318},"jobstr":"{\"class\":\"DistributionWorker\",\"args\":[100624626362482119],\"retry\":true,\"queue\":\"default\",\"jid\":\"c03e221c507a6f3fa84f4590\",\"created_at\":1535409948.1974733,\"enqueued_at\":1535410306.8475788,\"error_message\":\"undefined method `reblogs_count' for #<Status:0x000055cd34a5c0d8>\\nDid you mean?  reblogs\",\"error_class\":\"NoMethodError\",\"failed_at\":1535409948.2260487,\"retry_count\":3,\"retried_at\":1535410096.6493318}"}
2018-08-27T22:51:46.881Z 7 TID-gpxk1e0sr WARN: NoMethodError: undefined method `reblogs_count' for #<Status:0x000055cd3252c768>
Did you mean?  reblogs
2018-08-27T22:51:46.881Z 7 TID-gpxk1e0sr WARN: /mastodon/vendor/bundle/ruby/2.4.0/gems/activemodel-5.2.0/lib/active_model/attribute_methods.rb:430:in `method_missing'
/mastodon/vendor/bundle/ruby/2.4.0/gems/active_model_serializers-0.10.7/lib/active_model/serializer.rb:381:in `read_attribute_for_serialization'
/mastodon/vendor/bundle/ruby/2.4.0/gems/active_model_serializers-0.10.7/lib/active_model/serializer/field.rb:23:in `value'
/mastodon/vendor/bundle/ruby/2.4.0/gems/active_model_serializers-0.10.7/lib/active_model/serializer.rb:332:in `block in attributes'
/mastodon/vendor/bundle/ruby/2.4.0/gems/active_model_serializers-0.10.7/lib/active_model/serializer.rb:329:in `each'
/mastodon/vendor/bundle/ruby/2.4.0/gems/active_model_serializers-0.10.7/lib/active_model/serializer.rb:329:in `each_with_object'
/mastodon/vendor/bundle/ruby/2.4.0/gems/active_model_serializers-0.10.7/lib/active_model/serializer.rb:329:in `attributes'
/mastodon/vendor/bundle/ruby/2.4.0/gems/active_model_serializers-0.10.7/lib/active_model/serializer.rb:392:in `attributes_hash'
/mastodon/vendor/bundle/ruby/2.4.0/gems/active_model_serializers-0.10.7/lib/active_model/serializer.rb:360:in `serializable_hash'
/mastodon/vendor/bundle/ruby/2.4.0/gems/active_model_serializers-0.10.7/lib/active_model_serializers/adapter/attributes.rb:7:in `serializable_hash'
/mastodon/vendor/bundle/ruby/2.4.0/gems/active_model_serializers-0.10.7/lib/active_model_serializers/adapter/base.rb:59:in `as_json'
/mastodon/vendor/bundle/ruby/2.4.0/gems/active_model_serializers-0.10.7/lib/active_model_serializers/serializable_resource.rb:8:in `as_json'
/mastodon/vendor/bundle/ruby/2.4.0/gems/active_model_serializers-0.10.7/lib/active_model_serializers/logging.rb:69:in `block (3 levels) in notify'
/mastodon/vendor/bundle/ruby/2.4.0/gems/activesupport-5.2.0/lib/active_support/callbacks.rb:109:in `block in run_callbacks'
/mastodon/vendor/bundle/ruby/2.4.0/gems/active_model_serializers-0.10.7/lib/active_model_serializers/logging.rb:22:in `block (3 levels) in instrument_rendering'
/mastodon/vendor/bundle/ruby/2.4.0/gems/active_model_serializers-0.10.7/lib/active_model_serializers/logging.rb:79:in `block in notify_render'
/mastodon/vendor/bundle/ruby/2.4.0/gems/activesupport-5.2.0/lib/active_support/notifications.rb:170:in `instrument'
/mastodon/vendor/bundle/ruby/2.4.0/gems/active_model_serializers-0.10.7/lib/active_model_serializers/logging.rb:78:in `notify_render'
/mastodon/vendor/bundle/ruby/2.4.0/gems/active_model_serializers-0.10.7/lib/active_model_serializers/logging.rb:21:in `block (2 levels) in instrument_rendering'
/mastodon/vendor/bundle/ruby/2.4.0/gems/active_model_serializers-0.10.7/lib/active_model_serializers/logging.rb:95:in `block in tag_logger'
/mastodon/vendor/bundle/ruby/2.4.0/gems/activesupport-5.2.0/lib/active_support/tagged_logging.rb:71:in `block in tagged'
/mastodon/vendor/bundle/ruby/2.4.0/gems/activesupport-5.2.0/lib/active_support/tagged_logging.rb:28:in `tagged'
/mastodon/vendor/bundle/ruby/2.4.0/gems/activesupport-5.2.0/lib/active_support/tagged_logging.rb:71:in `tagged'
/mastodon/vendor/bundle/ruby/2.4.0/gems/active_model_serializers-0.10.7/lib/active_model_serializers/logging.rb:95:in `tag_logger'
/mastodon/vendor/bundle/ruby/2.4.0/gems/active_model_serializers-0.10.7/lib/active_model_serializers/logging.rb:20:in `block in instrument_rendering'
/mastodon/vendor/bundle/ruby/2.4.0/gems/activesupport-5.2.0/lib/active_support/callbacks.rb:118:in `instance_exec'
/mastodon/vendor/bundle/ruby/2.4.0/gems/activesupport-5.2.0/lib/active_support/callbacks.rb:118:in `block in run_callbacks'
/mastodon/vendor/bundle/ruby/2.4.0/gems/activesupport-5.2.0/lib/active_support/callbacks.rb:136:in `run_callbacks'
/mastodon/vendor/bundle/ruby/2.4.0/gems/active_model_serializers-0.10.7/lib/active_model_serializers/logging.rb:68:in `block (2 levels) in notify'
/mastodon/app/lib/inline_renderer.rb:21:in `render'
/mastodon/app/lib/inline_renderer.rb:25:in `render'
/mastodon/app/services/fan_out_on_write_service.rb:69:in `render_anonymous_payload'
/mastodon/app/services/fan_out_on_write_service.rb:11:in `call'
/mastodon/app/workers/distribution_worker.rb:7:in `perform'
/mastodon/vendor/bundle/ruby/2.4.0/gems/sidekiq-5.1.3/lib/sidekiq/processor.rb:187:in `execute_job'
/mastodon/vendor/bundle/ruby/2.4.0/gems/sidekiq-5.1.3/lib/sidekiq/processor.rb:169:in `block (2 levels) in process'
/mastodon/vendor/bundle/ruby/2.4.0/gems/sidekiq-5.1.3/lib/sidekiq/middleware/chain.rb:128:in `block in invoke'
/mastodon/app/lib/sidekiq_error_handler.rb:5:in `call'
/mastodon/vendor/bundle/ruby/2.4.0/gems/sidekiq-5.1.3/lib/sidekiq/middleware/chain.rb:130:in `block in invoke'
/mastodon/vendor/bundle/ruby/2.4.0/gems/sidekiq-unique-jobs-5.0.10/lib/sidekiq_unique_jobs/server/middleware.rb:17:in `call'
/mastodon/vendor/bundle/ruby/2.4.0/gems/sidekiq-5.1.3/lib/sidekiq/middleware/chain.rb:130:in `block in invoke'
/mastodon/vendor/bundle/ruby/2.4.0/gems/sidekiq-5.1.3/lib/sidekiq/middleware/chain.rb:133:in `invoke'
/mastodon/vendor/bundle/ruby/2.4.0/gems/sidekiq-5.1.3/lib/sidekiq/processor.rb:168:in `block in process'
/mastodon/vendor/bundle/ruby/2.4.0/gems/sidekiq-5.1.3/lib/sidekiq/processor.rb:139:in `block (6 levels) in dispatch'
/mastodon/vendor/bundle/ruby/2.4.0/gems/sidekiq-5.1.3/lib/sidekiq/job_retry.rb:98:in `local'
/mastodon/vendor/bundle/ruby/2.4.0/gems/sidekiq-5.1.3/lib/sidekiq/processor.rb:138:in `block (5 levels) in dispatch'
/mastodon/vendor/bundle/ruby/2.4.0/gems/sidekiq-5.1.3/lib/sidekiq/rails.rb:42:in `block in call'
/mastodon/vendor/bundle/ruby/2.4.0/gems/activesupport-5.2.0/lib/active_support/execution_wrapper.rb:87:in `wrap'
/mastodon/vendor/bundle/ruby/2.4.0/gems/activesupport-5.2.0/lib/active_support/reloader.rb:73:in `block in wrap'
/mastodon/vendor/bundle/ruby/2.4.0/gems/activesupport-5.2.0/lib/active_support/execution_wrapper.rb:87:in `wrap'
/mastodon/vendor/bundle/ruby/2.4.0/gems/activesupport-5.2.0/lib/active_support/reloader.rb:72:in `wrap'
/mastodon/vendor/bundle/ruby/2.4.0/gems/sidekiq-5.1.3/lib/sidekiq/rails.rb:41:in `call'
/mastodon/vendor/bundle/ruby/2.4.0/gems/sidekiq-5.1.3/lib/sidekiq/processor.rb:134:in `block (4 levels) in dispatch'
/mastodon/vendor/bundle/ruby/2.4.0/gems/sidekiq-5.1.3/lib/sidekiq/processor.rb:199:in `stats'
/mastodon/vendor/bundle/ruby/2.4.0/gems/sidekiq-5.1.3/lib/sidekiq/processor.rb:129:in `block (3 levels) in dispatch'
/mastodon/vendor/bundle/ruby/2.4.0/gems/sidekiq-5.1.3/lib/sidekiq/job_logger.rb:8:in `call'
/mastodon/vendor/bundle/ruby/2.4.0/gems/sidekiq-5.1.3/lib/sidekiq/processor.rb:128:in `block (2 levels) in dispatch'
/mastodon/vendor/bundle/ruby/2.4.0/gems/sidekiq-5.1.3/lib/sidekiq/job_retry.rb:73:in `global'
/mastodon/vendor/bundle/ruby/2.4.0/gems/sidekiq-5.1.3/lib/sidekiq/processor.rb:127:in `block in dispatch'
/mastodon/vendor/bundle/ruby/2.4.0/gems/sidekiq-5.1.3/lib/sidekiq/logging.rb:48:in `with_context'
/mastodon/vendor/bundle/ruby/2.4.0/gems/sidekiq-5.1.3/lib/sidekiq/logging.rb:42:in `with_job_hash_context'
/mastodon/vendor/bundle/ruby/2.4.0/gems/sidekiq-5.1.3/lib/sidekiq/processor.rb:126:in `dispatch'
/mastodon/vendor/bundle/ruby/2.4.0/gems/sidekiq-5.1.3/lib/sidekiq/processor.rb:167:in `process'
/mastodon/vendor/bundle/ruby/2.4.0/gems/sidekiq-5.1.3/lib/sidekiq/processor.rb:85:in `process_one'
/mastodon/vendor/bundle/ruby/2.4.0/gems/sidekiq-5.1.3/lib/sidekiq/processor.rb:73:in `run'
/mastodon/vendor/bundle/ruby/2.4.0/gems/sidekiq-5.1.3/lib/sidekiq/util.rb:16:in `watchdog'
/mastodon/vendor/bundle/ruby/2.4.0/gems/sidekiq-5.1.3/lib/sidekiq/util.rb:25:in `block in safe_thread'
```

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [x] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by csos95** [comment]
Actually I'm just bad at reading instructions.
On my dockerfile I only changed the tootsuite/mastodon image for the web service, not the other services.
I didn't read the instructions thoroughly and didn't realize the the streaming and sidekiq services use the same image.

So the issue was that those were running a 6 week old image and the web service was running v2.5.0rc1
Now I'm kind of surprised that this didn't break earlier through two other upgrades.
