### ISSUE TITLE
Mastodon timeline not working with 1.4rc1

### ISSUE THREAD

**Issue by tcitworld** [tootsuite/mastodon#3188]
Logs show : 

```
May 20 20:26:17 npm[25651]: verb 5c34fe9e-eb3a-41f4-a933-9a4a13f3b723 Starting stream from timeline:1 for 1
May 20 20:26:17 bundle[25849]: [948d73da-245f-4ac6-a9f4-890e13fd45da] method=GET path=/api/v1/timelines/home format=html controller=Api::V1::TimelinesController action=home status=500 error='NoMethodError: undefined method `conversation_id' for #<Status:0x00563a5cd9f430>
May 20 20:26:17 bundle[25849]: Did you mean?  conversation
May 20 20:26:17 bundle[25849]: conversation=' duration=276.10 view=0.00 db=38.64
May 20 20:26:17 bundle[25849]: [948d73da-245f-4ac6-a9f4-890e13fd45da]
May 20 20:26:17 bundle[25849]: [948d73da-245f-4ac6-a9f4-890e13fd45da] NoMethodError (undefined method `conversation_id' for #<Status:0x00563a5cd9f430>
May 20 20:26:17 bundle[25849]: Did you mean?  conversation
May 20 20:26:17 bundle[25849]: conversation=):
May 20 20:26:17 bundle[25849]: [948d73da-245f-4ac6-a9f4-890e13fd45da]
May 20 20:26:17 bundle[25849]: [948d73da-245f-4ac6-a9f4-890e13fd45da] app/controllers/api_controller.rb:101:in `map'
May 20 20:26:17 bundle[25849]: [948d73da-245f-4ac6-a9f4-890e13fd45da] app/controllers/api_controller.rb:101:in `set_maps'
May 20 20:26:17 bundle[25849]: [948d73da-245f-4ac6-a9f4-890e13fd45da] app/controllers/api/v1/timelines_controller.rb:13:in `home'
May 20 20:26:17 bundle[25849]: [bfe4aa14-405c-4793-8b75-523b3b9a804e] method=GET path=/api/v1/notifications format=html controller=Api::V1::NotificationsController action=index status=500 error='NoMethodError: undefined method `conversation_id' for #<Status:0x007fe15c12b0c0>
May 20 20:26:17 bundle[25849]: Did you mean?  conversation
May 20 20:26:17 bundle[25849]: conversation=' duration=350.90 view=0.00 db=30.78
May 20 20:26:17 bundle[25849]: [bfe4aa14-405c-4793-8b75-523b3b9a804e]
May 20 20:26:17 bundle[25849]: [bfe4aa14-405c-4793-8b75-523b3b9a804e] NoMethodError (undefined method `conversation_id' for #<Status:0x007fe15c12b0c0>
May 20 20:26:17 bundle[25849]: Did you mean?  conversation
May 20 20:26:17 bundle[25849]: conversation=):
May 20 20:26:17 bundle[25849]: [bfe4aa14-405c-4793-8b75-523b3b9a804e]
May 20 20:26:17 bundle[25849]: [bfe4aa14-405c-4793-8b75-523b3b9a804e] app/controllers/api_controller.rb:101:in `map'
May 20 20:26:17 bundle[25849]: [bfe4aa14-405c-4793-8b75-523b3b9a804e] app/controllers/api_controller.rb:101:in `set_maps'
May 20 20:26:17 bundle[25849]: [bfe4aa14-405c-4793-8b75-523b3b9a804e] app/controllers/api/v1/notifications_controller.rb:16:in `index'
```

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [x] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by tcitworld** [comment]
Fixed by doing the migrations.

**Comment by aral** [comment]
I have the same issue after the 1.4.1 upgrade and I ran the migrations. Any thoughts?

**Comment by aral** [comment]
OK, so restarting the containers fixed it.
