### ISSUE TITLE
Error: Cannot find module "react-router-scroll-4"

### ISSUE THREAD

**Issue by LudovicRousseau** [tootsuite/mastodon#6051]
After upgrade from 2.0.0 to 2.1.0 the web interface does not work any more.
I only get an empty screen. From the Firefox Console I get:

```
Error: Cannot find module "react-router-scroll-4"
Stack trace:
[251]@https://pouet.xxxx.fr/packs/application-732b244c60cb8ae5ab99.js:1:16875
t@https://pouet.xxxx.fr/packs/common-cf58dbc091dff5a29b03.js:1:96
[626]@https://pouet.xxxx.fr/packs/application-732b244c60cb8ae5ab99.js:1:63365
t@https://pouet.xxxx.fr/packs/common-cf58dbc091dff5a29b03.js:1:96
[625]@https://pouet.xxxx.fr/packs/application-732b244c60cb8ae5ab99.js:1:62018
t@https://pouet.xxxx.fr/packs/common-cf58dbc091dff5a29b03.js:1:96
[624]/<@https://pouet.xxxx.fr/packs/application-732b244c60cb8ae5ab99.js:1:61469
```

The Android application Mastalab works fine. The problem is only with the web interface.

I guess I failed something during the upgrade. From the upgrade output I got some errors:
```
ERROR in ./app/javascript/mastodon/components/scrollable_list.js
Module not found: Error: Can't resolve 'react-router-scroll-4' in '/home/mastodon/live/app/javascript/mastodon/components'
 @ ./app/javascript/mastodon/components/scrollable_list.js 10:0-56
 @ ./app/javascript/mastodon/features/notifications/index.js
 @ ./app/javascript/mastodon/features/ui/util/async-components.js
 @ ./app/javascript/mastodon/features/ui/index.js
 @ ./app/javascript/mastodon/containers/mastodon.js
 @ ./app/javascript/mastodon/main.js
 @ ./app/javascript/packs/application.js

ERROR in ./app/javascript/mastodon/containers/mastodon.js
Module not found: Error: Can't resolve 'react-router-scroll-4' in '/home/mastodon/live/app/javascript/mastodon/containers'
 @ ./app/javascript/mastodon/containers/mastodon.js 11:0-54
 @ ./app/javascript/mastodon/main.js
 @ ./app/javascript/packs/application.js
[...]
```

I tried to redo the commands (in the correct order) for the upgrade but that does not fix the issue.
Is there a way to force a rebuild of the precompilation?

```
$ bundle install
Using rake 12.3.0
Using concurrent-ruby 1.0.5
Using i18n 0.9.1
Using minitest 5.10.3
Using thread_safe 0.3.6
Using tzinfo 1.2.4
Using activesupport 5.1.4
Using builder 3.2.3
Using erubi 1.7.0
Using mini_portile2 2.3.0
Using nokogiri 1.8.1
Using rails-dom-testing 2.0.3
Using crass 1.0.3
Using loofah 2.1.1
Using rails-html-sanitizer 1.0.3
Using actionview 5.1.4
Using rack 2.0.3
Using rack-test 0.8.2
Using actionpack 5.1.4
Using nio4r 2.1.0
Using websocket-extensions 0.1.3
Using websocket-driver 0.6.5
Using actioncable 5.1.4
Using globalid 0.4.1
Using activejob 5.1.4
Using mini_mime 1.0.0
Using mail 2.7.0
Using actionmailer 5.1.4
Using activemodel 5.1.4
Using case_transform 0.2
Using jsonapi-renderer 0.2.0
Using active_model_serializers 0.10.7
Using arel 8.0.0
Using activerecord 5.1.4
Using public_suffix 3.0.1
Using addressable 2.5.2
Using encryptor 3.0.0
Using attr_encrypted 3.0.3
Using climate_control 0.2.0
Using cocaine 0.5.8
Using av 0.9.0
Using aws-sigv4 1.0.2
Using jmespath 1.3.1
Using aws-sdk-core 2.10.100
Using aws-sdk-resources 2.10.100
Using aws-sdk 2.10.100
Using bcrypt 3.1.11
Using msgpack 1.1.0
Using bootsnap 1.1.5
Using browser 2.5.2
Using bundler 1.16.0
Using charlock_holmes 0.7.5
Using chunky_png 1.3.8
Using ffi 1.9.18
Using cld3 3.2.1
Using colorize 0.8.1
Using connection_pool 2.2.1
Using orm_adapter 0.5.0
Using method_source 0.9.0
Using thor 0.20.0
Using railties 5.1.4
Using responders 2.4.0
Using warden 1.2.7
Using devise 4.3.0
Using rotp 2.1.2
Using devise-two-factor 3.0.2
Using unf_ext 0.0.7.4
Using unf 0.1.4
Using domain_name 0.5.20170404
Using doorkeeper 4.2.6
Using dotenv 2.2.1
Using dotenv-rails 2.2.1
Using et-orbi 1.0.8
Using excon 0.59.0
Using execjs 2.7.0
Using fast_blank 1.0.0
Using formatador 0.2.5
Using fog-core 1.45.0
Using multi_json 1.12.2
Using fog-json 1.0.2
Using fog-local 0.4.0
Using ipaddress 0.8.3
Using fog-openstack 0.1.22
Using http-cookie 1.0.3
Using http-form_data 1.0.3
Using http_parser.rb 0.6.0
Using http 2.2.2
Using oj 3.3.9
Using goldfinger 2.0.1
Using temple 0.8.0
Using tilt 2.0.8
Using hamlit 2.8.5
Using hamlit-rails 0.2.0
Using hamster 3.0.0
Using hiredis 0.6.1
Using hkdf 0.3.0
Using htmlentities 4.3.4
Using http_accept_language 2.1.1
Using httplog 0.99.7
Using idn-ruby 0.1.0
Using iso-639 0.2.8
Using link_header 0.0.8
Using rdf 2.2.12
Using json-ld 2.1.7
Using json-ld-preloaded 2.2.2
Using jwt 2.1.0
Using kaminari-core 1.1.1
Using kaminari-actionview 1.1.1
Using kaminari-activerecord 1.1.1
Using kaminari 1.1.1
Using request_store 1.3.2
Using lograge 0.7.1
Using redis 3.3.5
Using mario-redis-lock 1.2.0
Using mime-types-data 3.2016.0521
Using mime-types 3.1
Using mimemagic 0.3.2
Using nokogumbo 1.4.13
Using rack-protection 2.0.0
Using sidekiq 5.0.5
Using statsd-ruby 1.2.1
Using nsa 0.2.4
Using openssl 2.0.6
Using ostatus2 2.0.1
Using ox 2.8.2
Using paperclip 5.1.0
Using paperclip-av-transcoder 0.6.4
Using pg 0.21.0
Using pghero 1.7.0
Using pkg-config 1.2.8
Using puma 3.11.0
Using pundit 1.1.0
Using rack-attack 5.0.1
Using rack-cors 0.4.1
Using rack-proxy 0.6.2
Using rack-timeout 0.4.2
Using sprockets 3.7.1
Using sprockets-rails 3.2.1
Using rails 5.1.4
Using rails-i18n 5.0.4
Using rails-settings-cached 0.6.6
Using rdf-normalize 0.3.2
Using redis-store 1.4.1
Using redis-rack 2.0.3
Using redis-actionpack 5.0.2
Using redis-activesupport 5.0.4
Using redis-namespace 1.6.0
Using redis-rails 5.0.2
Using rqrcode 0.10.1
Using ruby-oembed 0.12.0
Using rufus-scheduler 3.4.2
Using sanitize 4.5.0
Using sidekiq-bulk 0.1.1
Using sidekiq-scheduler 2.1.10
Using sidekiq-unique-jobs 5.0.10
Using simple-navigation 4.0.5
Using simple_form 3.5.0
Using strong_migrations 0.1.9
Using twitter-text 1.14.7
Using tzinfo-data 1.2017.3
Using uglifier 3.2.0
Using webpacker 3.0.2
Using webpush 0.3.3
Bundle complete! 97 Gemfile dependencies, 163 gems now installed.
Gems in the groups development and test were not installed.
Bundled gems are installed into `./vendor/bundle`
```
```
$ yarn install
yarn install v1.2.1
[1/5] Resolving packages...
success Already up-to-date.
$ npm rebuild node-sass

> node-sass@4.7.2 install /home/mastodon/live/node_modules/node-sass
> node scripts/install.js

node-sass build Binary found at /home/mastodon/live/node_modules/node-sass/vendor/linux-x64-48/binding.node

> node-sass@4.7.2 postinstall /home/mastodon/live/node_modules/node-sass
> node scripts/build.js

Binary found at /home/mastodon/live/node_modules/node-sass/vendor/linux-x64-48/binding.node
Testing binary
Binary is fine
node-sass@4.7.2 /home/mastodon/live/node_modules/node-sass
Done in 6.64s.
```
```
$ RAILS_ENV=production bundle exec rails assets:precompile
Webpacker is installed 🎉 🍰
Using /home/mastodon/live/config/webpacker.yml file for setting up webpack paths
```

* * * *

- [X] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [X] This bug happens on a v2.1.0

**Comment by LudovicRousseau** [comment]
I reinstalled Mastodon from a clean ``git clone``. The service now works again.

It would help if a _forced_ re-generation of the assets was possible.

**Comment by MasterGroosha** [comment]
@LudovicRousseau Could you please explain how you performed a backup of all user data before fresh install?

**Comment by LudovicRousseau** [comment]
I reinstalled the code from git. I have not erased the database so the no need to backup/restore.
