### ISSUE TITLE
Occurs 500 when updated v1.6.1 to v2.0.0rc2

### ISSUE THREAD

**Issue by setter2002** [tootsuite/mastodon#5386]
500 error occured when access by webbrowser (firefox etc.).
What mean this ?

<pre><code>
web_1        | [9e2d1d54-33f8-4e7f-b1e8-874531259601] [active_model_serializers] Rendered ActiveModel::Serializer::CollectionSerializer with ActiveModelSerializers::Adapter::Attributes (435.05ms)
web_1        | [9e2d1d54-33f8-4e7f-b1e8-874531259601] method=GET path=/api/v1/timelines/public format=html controller=Api::V1::Timelines::PublicController action=show status=500 error='NoMethodError: undefined method `description' for #<MediaAttachment:0x000055b435d9f848>' duration=544.63 view=0.00 db=15.29
web_1        | [9e2d1d54-33f8-4e7f-b1e8-874531259601]   
web_1        | [9e2d1d54-33f8-4e7f-b1e8-874531259601] NoMethodError (undefined method `description' for #<MediaAttachment:0x000055b435d9f848>):
web_1        | [9e2d1d54-33f8-4e7f-b1e8-874531259601]   
web_1        | [9e2d1d54-33f8-4e7f-b1e8-874531259601] app/controllers/api/v1/timelines/public_controller.rb:10:in `show'
</code></pre>

**Comment by unarist** [comment]
Did you run `rake db:migrate`? The error says `description` is missing, and I think it's an attribute of MediaAttachment, which was added in v2.0.0.

**Comment by setter2002** [comment]
I am runnigng it on docker. 
And run at update 
<pre><code>
sudo docker-compose run --rm web rails db:migrate
</code></pre>

Thanks for your reply.

**Comment by setter2002** [comment]
I am runnigng it on docker. 
And run at update 
<pre><code>
sudo docker-compose run --rm web rails db:migrate
</code></pre>
but still 500 occurs.

Thanks for your reply.

**Comment by setter2002** [comment]
@ykzts 
Hi. 
Issue not yet solved.
But retry update later and check update logs.

**Comment by ykzts** [comment]
Oops, sorry😖

**Comment by setter2002** [comment]
Thanks :)

**Comment by setter2002** [comment]
I retry update. AndI see problems at db:migrate followed.
<pre><code>
...
-- remove_column(:mutes, :account_id)
rails aborted!
StandardError: An error has occurred, all later migrations canceled:

PG::InvalidTableDefinition: ERROR:  cannot drop inherited column "account_id"
: ALTER TABLE "mutes" DROP "account_id"
...
bin/rails:4:in `<main>'
ActiveRecord::StatementInvalid: PG::InvalidTableDefinition: ERROR:  cannot drop inherited column "account_id"
: ALTER TABLE "mutes" DROP "account_id"
...
</code></pre>

What should I do?

**Comment by unarist** [comment]
Oh...looks like your db has reverted migration which only exists on pre-1.4 master.

See discussion and fixes on https://github.com/tootsuite/mastodon/pull/2634#issuecomment-298231516

**Comment by setter2002** [comment]
WOW! Thanks!
Update of my instance has completed.

Do it before update.
<pre><code>
$ sudo docker exec -it mastodon_db_1 /bin/sh
# su postgres
$ psql
postgres=#  ALTER TABLE blocks NO INHERIT block_mutes;
postgres=#  ALTER TABLE blocks DROP COLUMN block;
postgres=#  ALTER TABLE mutes NO INHERIT block_mutes;
postgres=#  ALTER TABLE mutes DROP COLUMN block;
postgres=#  DROP TABLE block_mutes;
postgres=#  DELETE FROM schema_migrations WHERE version='20180428000000';
</code></pre>

**Comment by unarist** [comment]
:smile:
