### ISSUE TITLE
Error with User.create on 2.4.3

### ISSUE THREAD

**Issue by nemsia** [tootsuite/mastodon#8000]
When i try to create user on registration closed instance
```
irb(main):003:0> user = User.create!(email: 'xxxxx@xxxx.xxx', password: 'xxxxxx', account: account)
Traceback (most recent call last):
        2: from (irb):3
        1: from app/models/user.rb:321:in `sanitize_languages'
NameError (undefined local variable or method `chosen_languages' for #<User:0x00005603ec7a78f8>)
```

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [x] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by Gargron** [comment]
You need db:migrate

**Comment by otih** [comment]
db:migrate failes with #8001

**Comment by nemsia** [comment]
db:migrate run just before the user.create:
https://github.com/nemsia/mastodon_ynh/blob/f4d64b2ed1a755d73dc15919f644d12439490a38/scripts/install#L230
