### ISSUE TITLE
500 on /api/v1/search

### ISSUE THREAD

**Issue by marcust** [tootsuite/mastodon#1670]
I manually installed on an arm64 (aarch64) machine at bd834add567fc0a0f3960385a7f9abe4324ff212. 

I get a HTTP 500 response when I use the search, the logs says
``` NoMethodError: undefined method `n=' for #<OpenSSL::PKey::RSA:0x00007f900e0910>
Did you mean?  n```

Plus a stacktrace
```
app/services/follow_remote_account_service.rb:42:in `call'
app/services/account_search_service.rb:21:in `call'
app/services/search_service.rb:15:in `call'
app/controllers/api/v1/search_controller.rb:7:in `index'
app/controllers/concerns/localized.rb:24:in `block in set_locale'
app/controllers/concerns/localized.rb:23:in `set_locale'
```

I'm not a Ruby person, but how I see it what is actually crashing is https://github.com/tootsuite/ostatus2/blob/master/lib/ostatus2/magic_key.rb#L8

Now I'm wondering what I broke and why a `OpenSSL::PKey::RSA` should have a `n` field/method at all, because I don't see anything about that in the documentation. 

Any idea what is broken?

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by happyjaxx** [comment]
I'm getting something very similar upon remote follows and searches on accounts ever since I updated to 1.1.2 24 hours ago (no docker, rebenv installed 2.4.1, bundle updated, yarn, rebuild, static gifs etc...):

```
Apr 15 23:07:11 mastodon bundle[14215]: [6dd21a91-a127-450e-b041-76d70e63b118] method=GET path=/authorize_follow format=html controller=AuthorizeFollowController action=new status=500 error='NoMethodError: undefined method `n=' for #<OpenSSL::PKey::RSA:0x00564xxxxxxxxxx>
Apr 15 23:07:11 mastodon bundle[14215]: Did you mean?  n' duration=318.63 view=0.00 db=2.83
Apr 15 23:07:11 mastodon bundle[14215]: [6dd21a91-a127-450e-b041-76d70e63b118]
Apr 15 23:07:11 mastodon bundle[14215]: [6dd21a91-a127-450e-b041-76d70e63b118] NoMethodError (undefined method `n=' for #<OpenSSL::PKey::RSA:0x00564xxxxxxxxxx>
Apr 15 23:07:11 mastodon bundle[14215]: Did you mean?  n):
Apr 15 23:07:11 mastodon bundle[14215]: [6dd21a91-a127-450e-b041-76d70e63b118]
Apr 15 23:07:11 mastodon bundle[14215]: [6dd21a91-a127-450e-b041-76d70e63b118] app/services/follow_remote_account_service.rb:49:in `call'
Apr 15 23:07:11 mastodon bundle[14215]: [6dd21a91-a127-450e-b041-76d70e63b118] app/controllers/authorize_follow_controller.rb:39:in `set_account_from_acct'
Apr 15 23:07:11 mastodon bundle[14215]: [6dd21a91-a127-450e-b041-76d70e63b118] app/controllers/authorize_follow_controller.rb:14:in `new'
Apr 15 23:07:11 mastodon bundle[14215]: [6dd21a91-a127-450e-b041-76d70e63b118] app/controllers/concerns/localized.rb:24:in `block in set_locale'
Apr 15 23:07:11 mastodon bundle[14215]: [6dd21a91-a127-450e-b041-76d70e63b118] app/controllers/concerns/localized.rb:23:in `set_locale'
```

Same, not a Ruby person, though, I've been looking around can see anything odd, we might have either forgotten something or are stumbling on a rare bug, dunno :-/

**Comment by Gargron** [comment]
It looks like the upgrade from Ruby 2.3.1 to 2.4.1 introduced an API change on the `OpenSSL::PKey::RSA` class: It has a new method `set_key`. 2.3.1 did not have a method like that, so I am assuming they closed down the `n` attribute to be read-only.

Well, this is unpleasant. Gotta write in a fix asap.

**Comment by happyjaxx** [comment]
Thank you so much :-) I was actually thinking of relaunching everything under 2.3.4 (as I had it running before) but, being as good as I am in ruby, I'd probably break everything :-)

**Comment by marcust** [comment]
That fixes it for me, thanks.

**Comment by happyjaxx** [comment]
@marcust You cloned ostatus2 and gem installed that ? or put the source in the Gemfile ?

**Comment by marcust** [comment]
@happyjaxx I put the github source in the Gemfile

**Comment by happyjaxx** [comment]
Done !
bundle install --no-deployment
bundle update
bundle install --deployment --without development test
(seems too nuts for old me, but again, I'm from the perl cpan era :-) )

services restarted, and now I can follow new accounts !
Thanks !

**Comment by happyjaxx** [comment]
Oh, it's been pushed to RubyGems in the meanwhile
