### ISSUE TITLE
db:migrate fail on empty table.

### ISSUE THREAD

**Issue by fenax** [tootsuite/mastodon#5329]
When updating from 1.6.1 to 2.0.0rc1
The update fails when trying to get the lowest id of the table oauth_access_grants which has 0 rows.

> -- exec_query("SELECT  \"oauth_access_grants\".\"id\" FROM \"oauth_access_grants\" ORDER BY \"oauth_access_grants\".\"id\" ASC LIMIT 1")
>    -> 0.0011s
> rails aborted!
> StandardError: An error has occurred, all later migrations canceled:
> 
> undefined method `[]' for nil:NilClass
> /home/mastodon/live/lib/mastodon/migration_helpers.rb:339:in `update_column_in_batches'
> /home/mastodon/live/lib/mastodon/migration_helpers.rb:530:in `rename_column_concurrently'
> /home/mastodon/live/lib/mastodon/migration_helpers.rb:546:in `change_column_type_concurrently'
> /home/mastodon/live/db/migrate/20170918125918_ids_to_bigints.rb:107:in `block in migrate_columns'
> /home/mastodon/live/db/migrate/20170918125918_ids_to_bigints.rb:101:in `each'
> /home/mastodon/live/db/migrate/20170918125918_ids_to_bigints.rb:101:in `migrate_columns'
> /home/mastodon/live/db/migrate/20170918125918_ids_to_bigints.rb:113:in `up'
> /home/mastodon/live/vendor/bundle/ruby/2.4.0/gems/activerecord-5.1.4/lib/active_record/migration.rb:795:in `exec_migration'
> /home/mastodon/live/vendor/bundle/ruby/2.4.0/gems/activerecord-5.1.4/lib/active_record/migration.rb:776:in `block (2 levels) in migrate'
> /home/mastodon/live/vendor/bundle/ruby/2.4.0/gems/activerecord-5.1.4/lib/active_record/migration.rb:775:in `block in migrate'
> /home/mastodon/live/vendor/bundle/ruby/2.4.0/gems/activerecord-5.1.4/lib/active_record/connection_adapters/abstract/connection_pool.rb:408:in `with_connection'
> /home/mastodon/live/vendor/bundle/ruby/2.4.0/gems/activerecord-5.1.4/lib/active_record/migration.rb:774:in `migrate'
> /home/mastodon/live/vendor/bundle/ruby/2.4.0/gems/strong_migrations-0.1.9/lib/strong_migrations/migration.rb:13:in `migrate'
> /home/mastodon/live/vendor/bundle/ruby/2.4.0/gems/activerecord-5.1.4/lib/active_record/migration.rb:953:in `migrate'
> /home/mastodon/live/vendor/bundle/ruby/2.4.0/gems/activerecord-5.1.4/lib/active_record/migration.rb:1230:in `block in execute_migration_in_transaction'
> /home/mastodon/live/vendor/bundle/ruby/2.4.0/gems/activerecord-5.1.4/lib/active_record/migration.rb:1300:in `ddl_transaction'
> /home/mastodon/live/vendor/bundle/ruby/2.4.0/gems/activerecord-5.1.4/lib/active_record/migration.rb:1229:in `execute_migration_in_transaction'
> /home/mastodon/live/vendor/bundle/ruby/2.4.0/gems/activerecord-5.1.4/lib/active_record/migration.rb:1201:in `block in migrate_without_lock'
> /home/mastodon/live/vendor/bundle/ruby/2.4.0/gems/activerecord-5.1.4/lib/active_record/migration.rb:1200:in `each'
> /home/mastodon/live/vendor/bundle/ruby/2.4.0/gems/activerecord-5.1.4/lib/active_record/migration.rb:1200:in `migrate_without_lock'
> /home/mastodon/live/vendor/bundle/ruby/2.4.0/gems/activerecord-5.1.4/lib/active_record/migration.rb:1148:in `block in migrate'
> /home/mastodon/live/vendor/bundle/ruby/2.4.0/gems/activerecord-5.1.4/lib/active_record/migration.rb:1317:in `with_advisory_lock'
> /home/mastodon/live/vendor/bundle/ruby/2.4.0/gems/activerecord-5.1.4/lib/active_record/migration.rb:1148:in `migrate'
> /home/mastodon/live/vendor/bundle/ruby/2.4.0/gems/activerecord-5.1.4/lib/active_record/migration.rb:1007:in `up'
> /home/mastodon/live/vendor/bundle/ruby/2.4.0/gems/activerecord-5.1.4/lib/active_record/migration.rb:985:in `migrate'
> /home/mastodon/live/vendor/bundle/ruby/2.4.0/gems/activerecord-5.1.4/lib/active_record/tasks/database_tasks.rb:171:in `migrate'
> /home/mastodon/live/vendor/bundle/ruby/2.4.0/gems/activerecord-5.1.4/lib/active_record/railties/databases.rake:58:in `block (2 levels) in <top (required)>'
> /home/mastodon/live/vendor/bundle/ruby/2.4.0/gems/railties-5.1.4/lib/rails/commands/rake/rake_command.rb:21:in `block in perform'
> /home/mastodon/live/vendor/bundle/ruby/2.4.0/gems/railties-5.1.4/lib/rails/commands/rake/rake_command.rb:18:in `perform'
> /home/mastodon/live/vendor/bundle/ruby/2.4.0/gems/railties-5.1.4/lib/rails/command.rb:46:in `invoke'
> /home/mastodon/live/vendor/bundle/ruby/2.4.0/gems/railties-5.1.4/lib/rails/commands.rb:16:in `<top (required)>'
> /home/mastodon/live/vendor/bundle/ruby/2.4.0/gems/bootsnap-1.1.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:17:in `require'
> /home/mastodon/live/vendor/bundle/ruby/2.4.0/gems/bootsnap-1.1.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:17:in `require'
> /home/mastodon/live/vendor/bundle/ruby/2.4.0/gems/activesupport-5.1.4/lib/active_support/dependencies.rb:292:in `block in require'
> /home/mastodon/live/vendor/bundle/ruby/2.4.0/gems/activesupport-5.1.4/lib/active_support/dependencies.rb:258:in `load_dependency'
> /home/mastodon/live/vendor/bundle/ruby/2.4.0/gems/activesupport-5.1.4/lib/active_support/dependencies.rb:292:in `require'
> bin/rails:4:in `<main>'

`
start_id = exec_query(start_arel.to_sql).to_hash.first['id'].to_i
`

**Comment by Gargron** [comment]
@aschmitz

**Comment by aschmitz** [comment]
Investigating.

**Comment by aschmitz** [comment]
Hm, that's an interesting potential bug. Your line numbers are off by one, which is a little weird, but anyway:

Back on line 317 (your 318, probably), we check to see if the estimated table size is zero. If Postgres reports that it's nonzero, we keep going, and hit the issue where `.first` returns `nil`. This should really only happen if you had a smallish number of rows and then deleted them (which in oauth_access_grants is super weird, because I think they're required for the webapp?), but anyway, it should be a relatively easy fix. I'll submit a PR shortly.
