### ISSUE TITLE
Browser client "TypeError: _httpLinkHeader2.default.parseParams is not a function"

### ISSUE THREAD

**Issue by greenmanspirit** [tootsuite/mastodon#1768]
[Issue text goes here].

After updating to v1.1.2, I get the following error every time I reload the browser window. I also don't have content in my home timeline and notifications. I can however see everything from Tusky.

TypeError: _httpLinkHeader2.default.parseParams is not a function
Stack trace:
[125]</_httpLinkHeader2.default.parseAttrs@https://hobaugh.social/assets/application-aa03a028705b4f8f4e268bee9297fd29b612c1706a8014df5cd9dc20eb567065.js:38:10966
[266]</Link.prototype.parse@https://hobaugh.social/assets/application-aa03a028705b4f8f4e268bee9297fd29b612c1706a8014df5cd9dc20eb567065.js:353:2541
[266]</Link.parse@https://hobaugh.social/assets/application-aa03a028705b4f8f4e268bee9297fd29b612c1706a8014df5cd9dc20eb567065.js:353:1914
[17]</exports.getLinks@https://hobaugh.social/assets/application-aa03a028705b4f8f4e268bee9297fd29b612c1706a8014df5cd9dc20eb567065.js:30:1601
refreshNotifications/</<@https://hobaugh.social/assets/application-aa03a028705b4f8f4e268bee9297fd29b612c1706a8014df5cd9dc20eb567065.js:29:13613
  application-aa03a028705b4f8f4e268bee9297fd29b612c1706a8014df5cd9dc20eb567065.js:41:10757
TypeError: _httpLinkHeader2.default.parseParams is not a function
Stack trace:
[125]</_httpLinkHeader2.default.parseAttrs@https://hobaugh.social/assets/application-aa03a028705b4f8f4e268bee9297fd29b612c1706a8014df5cd9dc20eb567065.js:38:10966
[266]</Link.prototype.parse@https://hobaugh.social/assets/application-aa03a028705b4f8f4e268bee9297fd29b612c1706a8014df5cd9dc20eb567065.js:353:2541
[266]</Link.parse@https://hobaugh.social/assets/application-aa03a028705b4f8f4e268bee9297fd29b612c1706a8014df5cd9dc20eb567065.js:353:1914
[17]</exports.getLinks@https://hobaugh.social/assets/application-aa03a028705b4f8f4e268bee9297fd29b612c1706a8014df5cd9dc20eb567065.js:30:1601
refreshTimeline/</<@https://hobaugh.social/assets/application-aa03a028705b4f8f4e268bee9297fd29b612c1706a8014df5cd9dc20eb567065.js:29:29905
  application-aa03a028705b4f8f4e268bee9297fd29b612c1706a8014df5cd9dc20eb567065.js:41:10757

- [X] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by hnrysmth** [comment]
This is probably another instance of #1647. There's a workaround where you can add a bit of whitespace or any other kind of meaningless edit to any JS file to trigger a rebuild that pulls in the updated version of http-link-header. Wondering if maybe that issue needs reopening or something until we come up with a better fix.

**Comment by greenmanspirit** [comment]
I did the following based on the other issue:
yarn install
yarn upgrade
RAILS_ENV=production bundle exec rails assets:clean
vim app/assets/javascripts/components/link_header.jsx to add a space
RAILS_ENV=production bundle exec rails assets:precompile
sudo systemctl restart mastodon-*.service

It is working now.
